###服务启动端口号
server:
  port: 8003
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: eureka-order
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka,http://127.0.0.1:8011/eureka

    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true

#Zookeeper注册服务配置
#server:
#  port: 8020
####服务别名----服务注册到注册中心名称
#spring:
#  application:
#    name: zk-order
#  cloud:
#    zookeeper:
#      connect-string: 127.0.0.1:2181

#Consul注册服务配置
#server:
#  port: 8512
#spring:
#  application:
#    name: consul-order
#  ####consul 注册中心地址
#  cloud:
#    consul:
#      host: 127.0.0.1
#      port: 8500
#      discovery:
#        hostname: 127.0.0.1
#        ###服务健康值检查
#        heartbeat:
#          enabled: true

##在springboot2.1之后使用spring framework5.1 对日志info级别记录少，debug级别多但不详细，所以打印mapping url需要设置TRACE级别
##logging:
##  level:
##    org.springframework.web: TRACE